# Generated by Django 4.2.30 on 2026-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pidx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
