# Generated by Django 4.2.30 on 2026-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('on_way', 'On the Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
    ]
