# Generated by Django 4.2.30 on 2026-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
