# Generated by Django 4.2.30 on 2026-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_riderprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
