# Generated by Django 4.2.30 on 2026-05-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_riderprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='api.riderprofile'),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
