# Generated by Django 4.2.30 on 2026-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_kharcha_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('cod', 'Cash on Delivery')], default='esewa', max_length=20),
        ),
    ]
