# Generated by Django 4.2.30 on 2026-07-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_group_sponsorship_and_kharcha_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='calorie_target',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
