# Generated by Django 4.2.30 on 2026-06-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_group_sponsorship_and_kharcha_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Carbohydrates in grams', max_digits=6),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Fat in grams', max_digits=6),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fiber',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Dietary fiber in grams', max_digits=6),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Protein in grams', max_digits=6),
        ),
    ]
